# Generated by Django 3.1.4 on 2021-01-31 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='emp_id',
            new_name='employee_id',
        ),
    ]
