# Generated by Django 3.1.4 on 2021-01-31 21:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20210131_2034'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Postion',
            new_name='Position',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='postion',
            new_name='position',
        ),
        migrations.AddField(
            model_name='staff',
            name='fully_time',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='hired_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
