# Generated by Django 3.1.4 on 2021-02-01 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20210131_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enroll',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school'),
        ),
    ]
