# Generated by Django 3.1.4 on 2021-02-02 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20210201_2224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='postions',
            new_name='positions',
        ),
    ]
