# Generated by Django 3.1.4 on 2021-01-28 21:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.IntegerField(choices=[('0', 'Semester'), ('1', 'Trimester')])),
                ('semester', models.IntegerField(choices=[(1, 'First Semester'), (2, 'Second Semester'), (3, 'Third Semester')])),
                ('season', models.CharField(choices=[('SU', 'Summer'), ('WI', 'Winter'), ('AU', 'Autumn'), ('SP', 'Spring')], max_length=2)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='GradeSchoolSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='InstructorCourseSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.academicyear')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.academicyear')),
                ('enrolls', models.ManyToManyField(to='school.Enroll')),
                ('instructor_course_schedules', models.ManyToManyField(to='academic.InstructorCourseSchedule')),
            ],
        ),
    ]
