# Generated by Django 3.1.4 on 2021-02-01 21:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicQuarter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quater', models.CharField(max_length=25)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.academicyear')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicQuarterActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('point', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='QuarterSectionStudentAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('absent', models.IntegerField(choices=[(0, 'With Excuse'), (1, 'Without Excuse'), (2, 'Subspended'), (3, 'Other')])),
                ('date', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.sectionstudent')),
            ],
        ),
        migrations.CreateModel(
            name='QuarterSectionStudentMark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('point', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quater_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.academicquarteractivity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.sectionstudent')),
            ],
        ),
        migrations.RemoveField(
            model_name='activitymark',
            name='section_enrollment',
        ),
        migrations.RemoveField(
            model_name='activitymark',
            name='section_instruction',
        ),
        migrations.DeleteModel(
            name='ActivityType',
        ),
        migrations.RemoveField(
            model_name='sectionactivity',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='sectionactivity',
            name='section_instruction',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='academic_year',
        ),
        migrations.DeleteModel(
            name='ActivityMark',
        ),
        migrations.DeleteModel(
            name='SectionActivity',
        ),
        migrations.AddField(
            model_name='academicquarteractivity',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.activity'),
        ),
        migrations.AddField(
            model_name='academicquarteractivity',
            name='quater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.academicquarter'),
        ),
        migrations.AddField(
            model_name='academicquarteractivity',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.schedule'),
        ),
        migrations.AddField(
            model_name='academicquarteractivity',
            name='section_instruction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.sectioninstructor'),
        ),
    ]
