# Generated by Django 3.1.4 on 2021-01-28 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduler', '0001_initial'),
        ('instructor', '0001_initial'),
        ('campus', '0002_auto_20210128_2146'),
        ('academic', '0001_initial'),
        ('institution', '0001_initial'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorcourseschedule',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.classroom'),
        ),
        migrations.AddField(
            model_name='instructorcourseschedule',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.course'),
        ),
        migrations.AddField(
            model_name='instructorcourseschedule',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.instructor'),
        ),
        migrations.AddField(
            model_name='instructorcourseschedule',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.schedule'),
        ),
        migrations.AddField(
            model_name='gradeschoolsection',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.academicyear'),
        ),
        migrations.AddField(
            model_name='gradeschoolsection',
            name='enrolls',
            field=models.ManyToManyField(to='school.Enroll'),
        ),
        migrations.AddField(
            model_name='gradeschoolsection',
            name='instructor_course_schedules',
            field=models.ManyToManyField(to='academic.InstructorCourseSchedule'),
        ),
        migrations.AddField(
            model_name='gradeschoolsection',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.campusstaff'),
        ),
        migrations.AddField(
            model_name='academicstatus',
            name='levels',
            field=models.ManyToManyField(to='institution.ISCEDLevel'),
        ),
        migrations.AlterUniqueTogether(
            name='instructorcourseschedule',
            unique_together={('academic_year', 'course', 'instructor')},
        ),
    ]
