# Generated by Django 3.1.4 on 2021-02-02 09:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_auto_20210201_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leadership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('postion', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='SectionGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='SectionInstructorLeadership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Leadership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.leadership')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.sectioninstructor')),
            ],
        ),
        migrations.CreateModel(
            name='SectionStudentLeadership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Leadership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.leadership')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.sectionstudent')),
            ],
        ),
        migrations.AlterField(
            model_name='activity',
            name='point',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.DeleteModel(
            name='GradeSchoolSection',
        ),
    ]
