# Generated by Django 3.1.4 on 2021-01-31 18:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institution', '0001_initial'),
        ('personal', '0001_initial'),
        ('assembly', '0001_initial'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=25)),
                ('elevation', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.address')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.institution')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolCampus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.campus')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('floor', models.PositiveIntegerField(blank=True, null=True)),
                ('dimension', models.CharField(blank=True, max_length=25, null=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.building')),
            ],
        ),
        migrations.CreateModel(
            name='CourseCampus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.campus')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.course')),
            ],
        ),
        migrations.CreateModel(
            name='CollegeCampus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.campus')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.college')),
            ],
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assembly.class')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.room')),
            ],
        ),
        migrations.CreateModel(
            name='CampusStaff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.campus')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.staff')),
            ],
        ),
        migrations.AddField(
            model_name='campus',
            name='schools',
            field=models.ManyToManyField(through='campus.SchoolCampus', to='school.School'),
        ),
        migrations.AddField(
            model_name='building',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.campus'),
        ),
    ]
