# Generated by Django 3.1.4 on 2021-02-02 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_auto_20210201_2136'),
        ('campus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='personal.address'),
        ),
        migrations.AlterField(
            model_name='coursecampus',
            name='campus',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='campus.campus'),
        ),
    ]
