# Generated by Django 3.1.4 on 2021-02-02 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20210202_0949'),
        ('campus', '0002_auto_20210202_0913'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='campusstaff',
            unique_together={('staff', 'campus')},
        ),
        migrations.AlterUniqueTogether(
            name='collegecampus',
            unique_together={('college', 'campus')},
        ),
        migrations.AlterUniqueTogether(
            name='schoolcampus',
            unique_together={('school', 'campus')},
        ),
    ]
