# Generated by Django 3.1.4 on 2021-01-31 18:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_one', models.CharField(max_length=255)),
                ('address_line_two', models.CharField(blank=True, max_length=255, null=True)),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('apt_building', models.CharField(blank=True, max_length=255, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('providence', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('label', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=25)),
                ('value', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='CountryState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=25, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('label', models.CharField(blank=True, max_length=10, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('issuer', models.CharField(blank=True, max_length=10, null=True)),
                ('validation_url', models.URLField(blank=True, null=True)),
                ('validation_code', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=25)),
                ('given_name', models.CharField(max_length=25)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('maiden_name', models.CharField(blank=True, max_length=25, null=True)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('X', 'Not Say'), ('O', 'Other')], max_length=2)),
                ('date_of_birth', models.DateField(max_length=255)),
                ('marital_status', models.CharField(blank=True, choices=[(None, '(NONE)'), ('DI', 'Divorced'), ('MA', 'Married'), ('SE', 'Separated'), ('SI', 'Single'), ('WI', 'Widowed')], max_length=2, null=True)),
                ('skin_color', models.CharField(blank=True, choices=[('IV', 'Ivory'), ('BE', 'Beige'), ('AB', 'Alabaster'), ('HO', 'Honey'), ('CT', 'Carotenoid'), ('TA', 'Tan'), ('CA', 'Caramel'), ('BR', 'Bronze'), ('MA', 'Mahogany'), ('CH', 'Chestnut'), ('BU', 'Buff'), ('PC', 'Peachescream'), ('UM', 'Umber'), ('PR', 'Praline'), ('EB', 'Espressobrown'), ('PO', 'Porcelain'), ('HI', 'Hickory'), ('MU', 'Mustard'), ('SA', 'Sable'), ('AL', 'Almond'), ('BI', 'Bisque'), ('TE', 'Teak'), ('CC', 'Cacao'), ('PE', 'Pecan'), ('SB', 'Saddlebrown')], max_length=2, null=True)),
                ('eyes_color', models.CharField(blank=True, choices=[(None, '(UNKNOWN)'), ('AR', 'Amber'), ('BK', 'Black'), ('BE', 'Blue'), ('BN', 'Brown'), ('GY', 'Gray'), ('GN', 'Green'), ('HL', 'Hazel'), ('RA', 'Red Albino')], max_length=2, null=True)),
                ('height', models.CharField(blank=True, max_length=255, null=True)),
                ('weight', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Suffix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suffix', models.CharField(blank=True, choices=[(None, '(NONE)'), ('SR', 'Sr.'), ('JR', 'Jr.'), ('01', 'I'), ('02', 'II'), ('03', 'III'), ('04', 'IV'), ('05', 'V'), ('06', 'VI'), ('07', 'VII'), ('08', 'VIII'), ('09', 'XI'), ('10', 'X'), ('XX', 'Request')], max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('abbr', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonalTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, default=0, null=True)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.personal')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.title')),
            ],
            options={
                'unique_together': {('personal', 'title')},
            },
        ),
        migrations.CreateModel(
            name='PersonalSuffix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, default=0, null=True)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.personal')),
                ('suffix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.suffix')),
            ],
            options={
                'unique_together': {('personal', 'suffix')},
            },
        ),
        migrations.CreateModel(
            name='PersonalDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.document')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.personal')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=10, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.contact')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.personal')),
            ],
            options={
                'unique_together': {('personal', 'contact')},
            },
        ),
        migrations.CreateModel(
            name='PersonalAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.address')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.personal')),
            ],
            options={
                'unique_together': {('personal', 'address')},
            },
        ),
        migrations.AddField(
            model_name='personal',
            name='addresses',
            field=models.ManyToManyField(through='personal.PersonalAddress', to='personal.Address'),
        ),
        migrations.AddField(
            model_name='personal',
            name='contacts',
            field=models.ManyToManyField(through='personal.PersonalContact', to='personal.Contact'),
        ),
        migrations.AddField(
            model_name='personal',
            name='documents',
            field=models.ManyToManyField(through='personal.PersonalDocument', to='personal.Document'),
        ),
        migrations.AddField(
            model_name='personal',
            name='nationality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.country'),
        ),
        migrations.AddField(
            model_name='personal',
            name='suffixes',
            field=models.ManyToManyField(through='personal.PersonalSuffix', to='personal.Suffix'),
        ),
        migrations.AddField(
            model_name='personal',
            name='titles',
            field=models.ManyToManyField(through='personal.PersonalTitle', to='personal.Title'),
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.country'),
        ),
    ]
