# Generated by Django 3.1.4 on 2021-02-01 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20210131_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='location',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalcontact',
            name='contact',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='personal.contact'),
        ),
    ]
