# Generated by Django 3.1.4 on 2021-01-26 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20210126_1413'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentparent',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='studentparent',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='studentparent',
            name='student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='parents',
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
        migrations.DeleteModel(
            name='StudentParent',
        ),
    ]
