# Generated by Django 3.1.4 on 2021-01-31 18:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='ISCEDLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(blank=True, choices=[('PS', 'Primary Education'), ('SS', 'Secondary Education'), ('PE', 'Postsecondary Education'), ('VS', 'Vocational Education'), ('TS', 'Technical Education')], max_length=2, null=True)),
                ('level', models.CharField(choices=[('PREK', 'Pre Kindergarden'), ('KIND', 'Kindergarden'), ('GRAD', 'Grade'), ('UNGR', 'Under Garduate'), ('PGRA', 'Garduate'), ('POST', 'Post Garduate'), ('VOCA', 'Vocational'), ('TECH', 'Technical')], max_length=4)),
                ('grade', models.CharField(max_length=10)),
                ('ages', models.CharField(max_length=4)),
                ('duration', models.CharField(max_length=6)),
                ('achievement', models.CharField(blank=True, choices=[('HD', 'High Shool Diploma'), ('AD', 'Associate Degree'), ('BD', 'Bachelor Degree'), ('MD', 'Master Degree'), ('PD', 'Phd'), ('AP', 'Advance Professional Degree')], max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.document')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.institution')),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.contact')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.institution')),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.address')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.institution')),
            ],
        ),
        migrations.AddField(
            model_name='institution',
            name='addresses',
            field=models.ManyToManyField(through='institution.InstitutionAddress', to='personal.Address'),
        ),
        migrations.AddField(
            model_name='institution',
            name='contacts',
            field=models.ManyToManyField(through='institution.InstitutionContact', to='personal.Contact'),
        ),
        migrations.AddField(
            model_name='institution',
            name='documents',
            field=models.ManyToManyField(through='institution.InstitutionDocument', to='personal.Document'),
        ),
    ]
