# Generated by Django 3.1.4 on 2021-01-31 19:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('achievement', models.CharField(blank=True, max_length=25, null=True)),
                ('duration', models.CharField(max_length=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='iscedlevel',
            name='achievement',
        ),
        migrations.AlterField(
            model_name='iscedlevel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='ProgramMap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.iscedlevel')),
                ('program', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='institution.program')),
            ],
        ),
    ]
