# Generated by Django 3.1.4 on 2021-01-31 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0002_auto_20210131_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='description',
            field=models.TextField(default='defaults'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='name',
            field=models.CharField(default='default', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='program',
            name='achievement',
            field=models.CharField(default='default', max_length=25),
            preserve_default=False,
        ),
    ]
