# Generated by Django 3.1.4 on 2021-01-31 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0003_auto_20210131_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='map',
            field=models.ManyToManyField(through='institution.ProgramMap', to='institution.ISCEDLevel'),
        ),
        migrations.AlterField(
            model_name='programmap',
            name='step',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
