# Generated by Django 3.1.4 on 2021-01-31 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0005_auto_20210131_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iscedlevel',
            name='grade',
            field=models.CharField(max_length=10),
        ),
    ]
